package org.jabref.serpapiAPI;

import org.jabref.serpapiAPI.searchClasses.SerpApiSearchException;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class FirstFunctionalityTest {

    SerpAPI serpAPI = new SerpAPI("yBhrrXwAAAAJ");

    FirstFunctionalityTest() throws SerpApiSearchException {
    }

    @Test
    void generateGeneralInformation() {
        List<String> expectedOutputGeneralInformation = Arrays.asList("Nome: Miguel Goulão", "Afiliações: Associate Professor, Faculdade de Ciências e Tecnologia, Universidade Nova de Lisboa, NOVA Lincs",
                "Interesses:", "\n    Software Engineering", "\n    Empirical Software Engineering", "\n    Experimental Software Engineering",
                "\n    Evidence - based Software Engineering");
        List<String> expectedOutputCoAuthors = Arrays.asList("Co-autores:\n",
                "    Name of Coauthor: Vasco Amaral\n" ,
                "    Link: https://scholar.google.com/citations?user=p6lbgbAAAAAJ&hl=en\n" ,
                "    Affiliations: Associate Professor, NOVA University of Lisbon\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Fernando Brito e Abreu\n" ,
                "    Link: https://scholar.google.com/citations?user=CCTGOawAAAAJ&hl=en\n" ,
                "    Affiliations: Associate Professor (ISCTE-IUL) & Researcher (ISTAR-IUL)\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Ankica Barišić\n" ,
                "    Link: https://scholar.google.com/citations?user=6_ocsX0AAAAJ&hl=en\n" ,
                "    Affiliations: Université Côte d'Azur / I3S / INRIA Kairos\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Joao Araujo\n" ,
                "    Link: https://scholar.google.com/citations?user=tP9cyo0AAAAJ&hl=en\n" ,
                "    Affiliations: Associate Professor, Universidade Nova de Lisboa\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Ana Moreira\n" ,
                "    Link: https://scholar.google.com/citations?user=uB4MBw4AAAAJ&hl=en\n" ,
                "    Affiliations: Universidade Nova de Lisboa\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Catarina Gralha\n" ,
                "    Link: https://scholar.google.com/citations?user=ETZuDKMAAAAJ&hl=en\n" ,
                "    Affiliations: Computer Science PhD, Universidade Nova de Lisboa\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Bruno Barroca\n" ,
                "    Link: https://scholar.google.com/citations?user=7q9lPDwAAAAJ&hl=en\n" ,
                "    Affiliations: No perfil Google Scholar não estão mencionadas afiliações.\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Alexandre Marcos Lins de Vasconcelos\n" ,
                "    Link: https://scholar.google.com/citations?user=uTLN0mUAAAAJ&hl=en\n" ,
                "    Affiliations: Professor Associado IV do Centro de Informática da UFPE\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Moharram Challenger\n" ,
                "    Link: https://scholar.google.com/citations?user=pINGpc8AAAAJ&hl=en\n" ,
                "    Affiliations: Professor, Dept. of Computer Science, University of Antwerp; and Lab Manager, Flanders Make, Belgium\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Carla Silva\n" ,
                "    Link: https://scholar.google.com/citations?user=G-6XtcIAAAAJ&hl=en\n" ,
                "    Affiliations: Associate Professor at the Centro de Informática, Universidade Federal de Pernambuco, Brazil\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Jordi Cabot\n" ,
                "    Link: https://scholar.google.com/citations?user=LaGRXwkAAAAJ&hl=en\n" ,
                "    Affiliations: ICREA Research Professor at Internet Interdisciplinary Institute (UOC)\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Geylani Kardas\n" ,
                "    Link: https://scholar.google.com/citations?user=01nmmBEAAAAJ&hl=en\n" ,
                "    Affiliations: Associate Professor of Computer Science, Ege University International Computer Institute\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Barış Tekin Tezel\n" ,
                "    Link: https://scholar.google.com/citations?user=4jE4siEAAAAJ&hl=en\n" ,
                "    Affiliations: Bilgisayar Bilimleri Bölümü, Dokuz Eylül Üniversitesi\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Dominique Blouin\n" ,
                "    Link: https://scholar.google.com/citations?user=QWOudnQAAAAJ&hl=en\n" ,
                "    Affiliations: Research Eer, Telecom Paris, Hasso-Plattner-Institut\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Manuel Wimmer\n" ,
                "    Link: https://scholar.google.com/citations?user=YZDY1psAAAAJ&hl=en\n" ,
                "    Affiliations: Johannes Kepler University Linz\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Paulo Carreira\n" ,
                "    Link: https://scholar.google.com/citations?user=z_yhTPgAAAAJ&hl=en\n" ,
                "    Affiliations: INESC-ID & Instituto Superior Técnico, Universidade Técnica de Lisboa\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Loli Burgueño\n" ,
                "    Link: https://scholar.google.com/citations?user=f8SuIjgAAAAJ&hl=en\n" ,
                "    Affiliations: Open University of Catalonia\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: David Ameller\n" ,
                "    Link: https://scholar.google.com/citations?user=wEU99lsAAAAJ&hl=en\n" ,
                "    Affiliations: Freelance researcher\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Xavier Franch\n" ,
                "    Link: https://scholar.google.com/citations?user=k6b-lLYAAAAJ&hl=en\n" ,
                "    Affiliations: Full Professor, Universitat Politècnica de Catalunya\n" ,
                "\n" ,
                "\n" ,
                "    Name of Coauthor: Henry Muccini\n" ,
                "    Link: https://scholar.google.com/citations?user=5n9E1cMAAAAJ&hl=en\n" ,
                "    Affiliations: Full Professor in Computer Science, University of L'Aquila");
        List<String> expectedOutputArticles = Arrays.asList("Artigos:\n" ,
                "    Title: Toward the design quality evaluation of object-oriented software systems\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:u5HHmVD_uO8C\n" ,
                "    Autores: F Brito e Abreu, M Goulão, R Esteves\n" ,
                "\n" ,
                "\n" ,
                "    Title: Coupling and cohesion as modularization drivers: Are we being over-persuaded?\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:u-x6o8ySG0sC\n" ,
                "    Autores: FB e Abreu, M Goulao\n" ,
                "\n" ,
                "\n" ,
                "    Title: The evolution of requirements practices in software startups\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:j5aT6aphRxQC\n" ,
                "    Autores: C Gralha, D Damian, A Wasserman, M Goulão, J Araújo\n" ,
                "\n" ,
                "\n" ,
                "    Title: Quality in Use of Domain Specific Languages: a Case Study\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:WF5omc3nYNoC\n" ,
                "    Autores: A Barišic, V Amaral, M Goulão, B Barroca\n" ,
                "\n" ,
                "\n" ,
                "    Title: The design of eiffel programs: Quantitative evaluation using the mood metrics\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:2osOgNQ5qMEC\n" ,
                "    Autores: FB Abreu, R Esteves, M Goulão\n" ,
                "\n" ,
                "\n" ,
                "    Title: Bridging the gap between Acme and UML 2.0 for CBD\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:d1gkVwhDpl0C\n" ,
                "    Autores: M Goulão, FB e Abreu\n" ,
                "\n" ,
                "\n" ,
                "    Title: Do Software Languages Engineers Evaluate their Languages?\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:M3ejUd6NZC8C\n" ,
                "    Autores: P Gabriel, M Goulão, V Amaral\n" ,
                "\n" ,
                "\n" ,
                "    Title: Usability driven DSL development with USE-ME\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:yJjnfzR0HrkC\n" ,
                "    Autores: A Barišić, V Amaral, M Goulão\n" ,
                "\n" ,
                "\n" ,
                "    Title: Usability Evaluation of Domain-Specific Languages\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:r0BpntZqJG4C\n" ,
                "    Autores: A Barišić, V Amaral, M Goulão\n" ,
                "\n" ,
                "\n" ,
                "    Title: Evaluating the Usability of Domain-Specific Languages\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:4JMBOYKVnBMC\n" ,
                "    Autores: A Barišić, V Amaral, M Goulão, B Barroca\n" ,
                "\n" ,
                "\n" ,
                "    Title: The quest for software components quality\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:9yKSN-GCB0IC\n" ,
                "    Autores: M Goulão, F Brito e Abreu\n" ,
                "\n" ,
                "\n" ,
                "    Title: Towards a component quality model\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:qjMakFHDy7sC\n" ,
                "    Autores: M Goulão, FB Abreu\n" ,
                "\n" ,
                "\n" ,
                "    Title: Formalizing metrics for COTS\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:UeHWp8X0CEIC\n" ,
                "    Autores: M Goulão, FB Abreu\n" ,
                "\n" ,
                "\n" ,
                "    Title: Software evolution prediction using seasonal time analysis: a comparative study\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:_FxGoFyzp5QC\n" ,
                "    Autores: M Goulão, N Fonte, M Wermelinger, F Brito e Abreu\n" ,
                "\n" ,
                "\n" ,
                "    Title: Software components evaluation: an overview\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:_kc_bZDykSQC\n" ,
                "    Autores: M Goulão, FB Abreu\n" ,
                "\n" ,
                "\n" ,
                "    Title: How to reach a usable DSL? Moving toward a Systematic Evaluation\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:NMxIlDl6LWMC\n" ,
                "    Autores: A Barišic, V Amaral, M Goulao, B Barroca\n" ,
                "\n" ,
                "\n" ,
                "    Title: Quality in model-driven engineering: a tertiary study\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:bXQfdp6S9ecC\n" ,
                "    Autores: M Goulão, V Amaral, M Mernik\n" ,
                "\n" ,
                "\n" ,
                "    Title: The GOODLY design language for MOOD2 metrics collection\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:IjCSPb-OGe4C\n" ,
                "    Autores: FB e Abreu, L Ochoa, M Goulão\n" ,
                "\n" ,
                "\n" ,
                "    Title: Quality of software requirements specification in agile projects: A cross-case analysis of six companies\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:cRMvf6lLvU8C\n" ,
                "    Autores: J Medeiros, A Vasconcelos, C Silva, M Goulão\n" ,
                "\n" ,
                "\n" ,
                "    Title: What is the impact of bad layout in the understandability of social goal models?\n" ,
                "    Link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=yBhrrXwAAAAJ&alert_preview_top_rm=2&citation_for_view=yBhrrXwAAAAJ:l6Q3WhenKVUC\n" ,
                "    Autores: M Santos, C Gralha, M Goulao, J Araújo, A Moreira, J Cambeiro");

        List<String> expectedOutput = expectedOutputGeneralInformation;
        expectedOutput.addAll(expectedOutputArticles);
        expectedOutput.addAll(expectedOutputCoAuthors);

        assertEquals(expectedOutput, serpAPI.getResultOfSearch());
    }
}
